### ISSUE TITLE
친구추가 버튼

### ISSUE THREAD

**Issue by FoocoJun** [finalproject-hanghae/DontBeWeak-FE#24]
친구추가 버튼 수정해서 RecordingPage에 넣어야 합니다.

있어야하는 기능

**Comment by INSOCCI** [comment]
넵! 해당 부분 수정해서 아까 추가 디자인 나온 것까지 View 반영하여 Release Branch에 Push 했습니다 :-)
오늘 자정까지 친구목록 모달창 부분까지 작업 완료해놓겠습니닷.
