### ISSUE TITLE
isAddFriend state 충돌현상

### ISSUE THREAD

**Issue by FoocoJun** [finalproject-hanghae/DontBeWeak-FE#50]
## 설명
친구 추가창에서 값 제거시 입력창 띠용?현상 있습니다.

 `isAddFriend` state가 두가지 용도로 사용되어 충돌되는 것 같습니다.

## 재현과정
- 친구추가를 누르면 isAddFriend 가 true로 바뀜
```
 // isAddFriend가 true로 변하게 해주는 함수
  const showFriendAddInput = () => {
    setIsAddFriend(true);
  };
```
- isAddFriend 가 true 면 등록창이 나타남.
```
{isAddFriend ? (
        // 등록할 친구 ID 입력창
```
- 💡값을 입력하면 isAddFriend에 담김 -> `isAddFriend = e.target.value // true`
```
 onChange={(e) => setIsAddFriend(e.target.value)}
```
결국 친구이름을 적으면 isAddFriend에 담기는데
- 다 지워서 공백이 되면 isAddFriend = "" // false
```
{isAddFriend ? (
        // 등록할 친구 ID 입력창
```

## 결과
창이 켜졌다가 값을 지워서 공백이 되면 창이 꺼지는 현상이 발생.

## 기대결과
친구 추가창에서 값 제거 시 입력창이 띠용하지 않기

**Comment by INSOCCI** [comment]
이슈 확인했습니다 :)

'setDisabled' 라는 state 생성하고 초기값을 true로 설정한 후,
onChange={(e) => setIsAddFriend(e.target.value)} 에서 
onChange={change} 로 변경하여 isAddFriend와 분리했습니다.

위 change 함수에 if를 활용하여 친구 추가 버튼 클릭 시 true가 되어 ID 입력창이 뜨도록 하되,
그 값이 공백일 땐 계속 true값을 유지하도록 해서 문제를 해결했습니다 !

다만...
+ 지금은 이 방법 밖에 떠오르지 않았기 때문에 더 효율적인(?) 코드가 있는지는 더 알아봐야할 것 같습니다.
+ chage 라는 함수명도 문제 해결을 위해 급하게 지은거라....ㅎㅎ 차후 Refactoring 진행하겠습니다.
