### ISSUE TITLE
주간 캘린더 기록 및 조회 이슈

### ISSUE THREAD

**Issue by INSOCCI** [finalproject-hanghae/DontBeWeak-FE#97]
[https://user-images.githubusercontent.com/105898246/187196848-3fac2bed-28dd-4653-a3a5-2f0170310083.mp4](url)

https://user-images.githubusercontent.com/105898246/187196914-3fce61b5-15b1-4d9a-9cef-f5918f05fb89.mp4

위 영상과 같이, 지난주(20220821~20220827) 캘린더 조회를 하는 도중에
오늘(20220829, 월요일) 먹은 영양제 체크 시 캘린더가 리렌더링 되지 않고 지난주 월요일에 
커스텀표시가 되고 있습니다. 

물론, 새로고침을 하면 이번주 캘린더가 뜨면서 체크 기록도 정상으로 돌아오긴 합니다 !
사용자 입장에선 이를 정보 반영의 문제로 자칫 오해할 수도 있을 것 같다는 생각이 들다가도...
굳이 다른 주의 캘린더에서 체크를 하는 사람이 과연 몇명이나 있을지에 대한 의문이 들고...
괜히 불필요한 렌더링이 되진 않을까 고민이 됩니다.

그래도 일단은 체크를 하면 다른 주에 있다가도 바로 이번주 캘린더에 반영된 것이 보일 수 있도록 하면 좋을 것 같습니다 :-)

**Comment by INSOCCI** [comment]
이슈 등록

**Comment by FoocoJun** [comment]
https://github.com/finalproject-hanghae/DontBeWeak-FE/pull/98

redux 제거를 통해 완료했습니다.
